alias py="python3"
alias auu="sudo apt update && sudo apt -y upgrade"
alias v="nvim"
alias vba="nvim ~/.bash_aliases"
alias vb="nvim ~/.bashrc"
alias vv="nvim ~/.config/nvim/init.vim"
alias dotfile="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
